
- include: mac.yml
  when: ansible_os_family == "Darwin"
- include: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora

- name: Install tmuxp
  pip: name=tmuxp state=latest
  when: tmux_install_tmuxp

- name: Install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ansible_env.HOME}}/.tmux/plugins/tpm"

- name: Copy .tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ansible_env.HOME}}/.tmux.conf"

