# Installation
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"
- include: mac.yml
  when: ansible_os_family == "Darwin"

# Plugin manager
- name: Makes sure autoload directory exists
  file: path="{{ansible_env.HOME}}/.vim/autoload" state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ansible_env.HOME}}/.vim/autoload/plug.vim"

# Snippets
- name: Makes sure UltiSnips directory exists
  file: path="{{ansible_env.HOME}}/.vim/UltiSnips" state=directory

- name: Copy all snippet files
  copy:
    src: "{{item}}"
    dest: "{{ ansible_env.HOME}}/.vim/UltiSnips/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "python.snippets"
    - "rst.snippets"
    - "javascript.snippets"

# Configuration
- name: Check if vimrc exists
  stat: path="{{ansible_env.HOME}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{ansible_env.HOME}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Copy vimrc
  copy:
    src: "vimrc"
    dest: "{{ansible_env.HOME}}/.vimrc"
    owner: root
    group: root
    mode: 0644

# - name: Install plugins
#   command: vim +PlugInstall +qall
#   when: vim_install_plugins
